# sudo apt update
# sudo apt-add-repository ppa:ansible/ansible
# sudo apt install ansible
# sudo apt install python3-pip
# sudo pip3 install --upgrade pip
#
# will also need Vault, set the env vars VAULT_ADDR and VAULT_TOKEN
#
# cephfs in order to see the status and streams
# cd ~/lasair-lsst/ansible
# change hosts.yml to new cephfs_nodes
# ansible-playbook --inventory-file=hosts.yml mount_cephfs.yml
---
- hosts: webserver
  gather_facts: no

  vars:
      settings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings')}}"

  tasks:
    - name: install python3-pip
      apt: 
          name: python3-pip
          state: present
          update_cache: true
      become: yes

    - name: upgrade pip3
      pip:
          name: pip
          executable: pip3
          state: latest

    - name: install apache2
      apt: 
          name: apache2
          state: present
          update_cache: true
      become: yes

    - name: install apache2-utils
      apt: 
          name: apache2-utils
          state: present
          update_cache: true
      become: yes

    - name: install apache2-dev
      apt: 
          name: apache2-dev
          state: present
          update_cache: true
      become: yes

    - name: install libexpat1
      apt: 
          name: libexpat1
          state: present
          update_cache: true
      become: yes

    - name: install ssl-cert
      apt: 
          name: ssl-cert
          state: present
          update_cache: true
      become: yes

    - name: install libmysqlclient-dev
      apt: 
          name: libmysqlclient-dev
          state: present
          update_cache: true
      become: yes

    - name: install swig-pip
      apt: 
          name: swig
          state: present
          update_cache: true
      become: yes

    - name: install mysql.connector
      pip: 
          executable: pip3 
          name: mysql-connector-python

    - name: install mysqlclient
      pip: 
          executable: pip3 
          name: mysqlclient

    - name: install django
      pip: 
          executable: pip3 
          name: django

    - name: install djangorestframework
      pip: 
          executable: pip3 
          name: djangorestframework

    - name: install pyephem
      pip: 
          executable: pip3 
          name: pyephem

    - name: install requests
      pip: 
          executable: pip3 
          name: requests

    - name: install MOCpy
      pip: 
          executable: pip3 
          name: MOCpy

    - name: install astropy
      pip: 
          executable: pip3 
          name: astropy

    - name: install confluent kafka
      pip: 
          executable: pip3 
          name: confluent_kafka

    - name: install cassandra client
      pip:
          executable: pip3 
          name: cassandra-driver
      become: yes

    - name: install postfix email
      apt:
          name: postfix
          state: present
          update_cache: true
      become: yes

    - name: install gkhtm
      pip: 
          executable: pip3 
          name: gkhtm
      become: yes

    - name: install gkutils
      pip: 
          executable: pip3 
          name: gkutils
      become: yes

    - name: install mod_wsgi-httpd
      pip: 
          executable: pip3 
          name: mod_wsgi-httpd
      become: yes

    - name: install mod_wsgi
      pip: 
          executable: pip3 
          name: mod_wsgi
      become: yes

    - name: Creates directory
      file:
          path: /home/ubuntu/mod_wsgi_space
          state: directory

    - name: Make sure the repo is up to date
      git:
          repo: https://github.com/lsst-uk/lasair-lsst-web.git
          dest: /home/ubuntu/lasair-lsst-web

    - name: settings.py for django
      template:
        src:  /home/ubuntu/lasair-lsst-web/src/lasair-webapp/lasair/lasair/settings.py.j2
        dest: /home/ubuntu/lasair-lsst-web/src/lasair-webapp/lasair/lasair/settings.py 
