# sudo apt update
# sudo apt-add-repository ppa:ansible/ansible
# sudo apt install ansible
# sudo apt install python3-pip
# sudo pip3 install --upgrade pip
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: install libraries
      apt: 
      with_items:
       - python3-pip
       - apache2
       - apache2-utils
       - apache2-dev
       - libexpat1
       - ssl-cert
       - libmysqlclient-dev
       - swig
      become: yes

    - name: install mysql.connector
      pip: 
          executable: pip3 
          name: mysql-connector-python

    - name: install django
      pip: 
          executable: pip3 
          name: django

    - name: install pyephem
      pip: 
          executable: pip3 
          name: pyephem

    - name: install requests
      pip: 
          executable: pip3 
          name: requests

    - name: install MOCpy
      pip: 
          executable: pip3 
          name: MOCpy

    - name: install astropy
      pip: 
          executable: pip3 
          name: astropy

    - name: install fastavro
      pip:
          executable: pip3
          name: fastavro
      become: yes

    - name: install mod-wsgi
      pip: 
          executable: pip3 
          name: mod-wsgi

    - name: configure mod-wsgi
      shell: 
         cmd: /home/ubuntu/.local/bin/mod_wsgi-express module-config > /etc/apache2/mods-available/wsgi.load
      become: yes

    - name: copy conf file
      shell: 
          cmd: cp ../conf/webserver.conf /etc/apache2/sites-available
      become: yes

    - name: link it from sites-enabled
      shell: 
          cmd: ln -s ../sites-available/webserver.conf webserver.conf
          chdir: /etc/apache2/sites-enabled
      become: yes
